In [3]:
import pandas as pd

In [4]:
question = 'Употребляли ли Вы различные напитки (пиво, вино, водку и др.) за последние 30 дней?'
index = ['Да', 'Нет']

df = {
    'Есть высшее': [1675, 1643],
    'Нет высшего': [2772, 3903]
}

pd.DataFrame(data=df, index=index)

     Есть высшее  Нет высшего
Да          1675         2772
Нет         1643         3903

In [5]:
question = 'Употребляли ли Вы различные напитки (пиво, вино, водку и др.) за последние 12 месяцев?'
index = ['Да', 'Нет']

df = {
    'Есть высшее': [2523, 795],
    'Нет высшего': [4347, 2327]
}

pd.DataFrame(data=df, index=index)

     Есть высшее  Нет высшего
Да          2523         4347
Нет          795         2327

In [6]:
question = 'Употребляли ли Вы различные напитки (пиво, вино, водку и др.) в течение жизни?'
index = ['Да', 'Нет']

df = {
    'Есть высшее': [2841, 477],
    'Нет высшего': [5378, 1296]
}

pd.DataFrame(data=df, index=index)

     Есть высшее  Нет высшего
Да          2841         5378
Нет          477         1296

In [7]:
question = 'Сколько раз за последние 30 дней (если такое вообще было) Вы выпивали подряд 5 и более стандартных порций?'
index = ['Такого не было', '1 раз', '2 раза', '3-5 раз', '6-9 раз', '10 раз и более']

df = {
    'Есть высшее': [1967, 753, 317, 217, 38, 23],
    'Нет высшего': [3381, 1630, 722, 554, 191, 186]
}

pd.DataFrame(data=df, index=index)

                Есть высшее  Нет высшего
Такого не было         1967         3381
1 раз                   753         1630
2 раза                  317          722
3-5 раз                 217          554
6-9 раз                  38          191
10 раз и более           23          186

In [8]:
# Процент курящих людей в регионе

north_west_fd = [
    ['Республика Карелия', 'Республика Коми', 'Архангельская область без авт. округа', "Ненецкий авт. округ", "Вологодская область", "Калининградская область", "Ленинградская область", "Мурманская область", "Новгородская область", "Псковская область", "г. Санкт-Петербург"],
    [29.3, 28.9, 29.5, 30.0, 25.5, 25.4, 29.5, 33.1, 31.4, 29.7, 21.6]
]

far_east_fd = [
    ["Республика Бурятия", "Республика Саха (Якутия)", "Забайкальский край", "Камчатский край", "Приморский край", "Хабаровский край", "Амурская область", "Магаданская область", "Сахалинская область", "Еврейская авт. область", "Чукотский авт. округ"],
    [30.5, 34.4, 36.3, 33.5, 28.5, 34.0, 33.0, 27.5, 34.1, 37.3, 39.0]
]

pd.Series(north_west_fd[1], index=north_west_fd[0])

Республика Карелия                       29.3
Республика Коми                          28.9
Архангельская область без авт. округа    29.5
Ненецкий авт. округ                      30.0
Вологодская область                      25.5
Калининградская область                  25.4
Ленинградская область                    29.5
Мурманская область                       33.1
Новгородская область                     31.4
Псковская область                        29.7
г. Санкт-Петербург                       21.6
dtype: float64

In [ ]:
# Процент пьющих людей

north_west_fd = [
    ['Республика Карелия', 'Республика Коми', 'Архангельская область без авт. округа', "Ненецкий авт. округ", "Вологодская область", "Калининградская область", "Ленинградская область", "Мурманская область", "Новгородская область", "Псковская область", "г. Санкт-Петербург"],
    [5.3, 4.7, 10.7, 3.6, 6.0, 4.2, 4.7, 8.3, 8.8, 4.5, 3.9]
]

far_east_fd = [
    ["Республика Бурятия", "Республика Саха (Якутия)", "Забайкальский край", "Камчатский край", "Приморский край", "Хабаровский край", "Амурская область", "Магаданская область", "Сахалинская область", "Еврейская авт. область", "Чукотский авт. округ"],
    [4.6, 3.6, 6.0, 6.0, 6.1, 10.0, 5.9, 5.9, 7.5, 11.5, 15.8]
]

volga_fg = [
    ["Республика Башкортостан", "Республика Марий Эл", "Республика Мордовия", "Республика Татарстан", "Удмуртская Республика", "Чувашская Республика", "Пермский край", "Кировская область", "Нижегородская область", "Оренбургская область", "Пензенская область", "Самарская область", "Саратовская область", "Ульяновская область"],
    [4.0, 4.1, 2.7, 2.6, 4.2, 3.6, 5.3, 4.4, 4.2, 3.7, 4.6, 4.2, 2.7, 3.4]
]